### ISSUE TITLE
:large_blue_diamond: [Epic] Component Discovery Feed Interface

### ISSUE THREAD

**Issue by TiffanyGYJ** [near/data-platform#19]
### Description
Add a 'components' tab next to 'all posts' and 'following'. The feed should look exactly like the posts feed, and have a 'post' saying 'I just published a Component A' with a user profile. The viewer should only see posts like this for people they follow. In case the don't follow anyone who publishes components, they see a prompt to find developers on the contributor board.

The implementation should use QueryAPI widgets indexer. The indexer should be efficient for filtering components from people the viewer follows.

### Success Criteria

```[tasklist]
### Child Issues
```

**Comment by xuan-ytr** [comment]
@TiffanyGYJ, could we define a few things for this feature are for traceability? I'm putting my assumptions in _italics_, please validate if correct and help me fill in the rest.
**Core questions**
* User - Who does the problem impact? Who are we building this feature for? _developers who work for founders? independent developers? OSS developers? (uncertain which type, or all)_
* Motivation - What is the user trying to accomplish? Their incentives? _Get the most up-to-date list of potentially useful components for their build when they log in to near.org; users may be incentivized by solving current development pain points and (do we have research to back this? I vaguely remember that we may have heard a signal for this during a developer interview)_
* Expected outcomes if this feature is successful?
* Problem - what user problem are we solving for?
* Impact - what downstream effects are caused by the problem? How severe? What impact is the product opportunity creating?
**Additional questions**
* When are the design and engineering deadlines?
* Do we have time for a quick round of internal user testing before committing to designs?
* How will we populate the component feed? How will it be updated?
* What are the default components to show for new users who haven't followed anyone? 
* Will this replace the sidebar on near.org page? (see attached)
<img width="902" alt="image" src="https://github.com/near/data-platform/assets/112567018/6e147882-7abb-4a17-a1be-da900c620fee">

Let me know if you prefer to chat about some of these items on a call before our next sync on Thursday so we can move into design explorations.

**Comment by xuan-ytr** [comment]
@Kevin101Zhang @TiffanyGYJ @sarahmills[ latest design iteration](https://www.figma.com/proto/tWVSAyZKWDzFyyGTI1jFAr/Component-Discovery?page-id=1150%3A592&type=design&node-id=1185-7632&viewport=-2225%2C581%2C0.5&t=oLYChYKXQk8JBaX2-1&scaling=min-zoom&mode=design), pending design review and sync with Kevin on interaction design. <img width="711" alt="image" src="https://github.com/near/data-platform/assets/112567018/14aeb02f-1902-4062-a4cc-1b8f65477207">
Functionality Notes:
- The component only view is now default
- The filters "latest" and "last commented" can be applied to either the full feed or the component update only feed

**Comment by xuan-ytr** [comment]
[Design in review](https://www.figma.com/proto/tWVSAyZKWDzFyyGTI1jFAr/Component-Discovery?page-id=1150%3A592&type=design&node-id=1220-13477&viewport=-1683%2C475%2C0.5&t=LbrVdfemqDCnR10A-1&scaling=scale-down-width&mode=design).

**Comment by xuan-ytr** [comment]
[V2 of design in review](https://www.figma.com/proto/tWVSAyZKWDzFyyGTI1jFAr/Component-Discovery?page-id=1150%3A592&type=design&node-id=1232-7260&viewport=-1782%2C1464%2C0.25&t=d8btFjJ96nj9EB9o-1&scaling=min-zoom&starting-point-node-id=1232%3A11028&mode=design)
[Design thinking worksheet](https://www.figma.com/proto/tWVSAyZKWDzFyyGTI1jFAr/Component-Discovery?page-id=1150%3A592&type=design&node-id=1214-3976&viewport=262%2C509%2C0.25&t=Zn3m0FleBymqhqFu-1&scaling=contain&starting-point-node-id=1232%3A11028&mode=design) (WIP summary of motivations, problems, outcomes)

**Comment by Kevin101Zhang** [comment]
blocked on
https://github.com/near/queryapi/issues/494

**Comment by xuan-ytr** [comment]
Completed design QA / fit & finish with @Kevin101Zhang today. [Spec here](https://www.figma.com/proto/tWVSAyZKWDzFyyGTI1jFAr/Component-Discovery?page-id=1150%3A592&type=design&node-id=1232-7260&viewport=-4442%2C2638%2C0.5&t=fMGuI1CuxaKpV3wN-1&scaling=min-zoom&starting-point-node-id=1232%3A11028&mode=design).

1. Decided to hide stars and forks from view unless a component has at least one star or one fork [done]
2. Swap out current icons for phosphor icons to adhere to design system. 

This feature is ready for production as soon as item 2 is done.
